### ISSUE TITLE
Run InVEST against its sample data

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#74] opened 2020-04-08 18:53 UTC
As maintainers of InVEST, we have a suite of software tests that ensure the model works as expected on precisely-constructed sample data.  As @dcdenu4 mentioned today on a call, it would be responsible for us to ensure that the model works as expected on the sample data that we ship with InVEST in addition to the tests for software functionality.

One aspect of this form of testing (_do binaries crash when running the model on sample data?_) is currently contained in `scripts/invest-autotest.py`, but perhaps it would be better to restructure this as a suite of tests that also can assert some summary statistics of the output files?  And, if so, how might we include these tests as a regular part of our development cycle in a way that doesn't dramatically extend the runtime of our tests?

This would be worth designing and reviewing before implementing in full.

**Comment by davemfish** [comment] 2020-04-23 22:44
I agree it is important to test models with their sample data before releasing, like we do with `invest-autotest.py`. I think that asserting the results of those runs are numerically the same as some expected values is redundant with our existing suite of regression tests. I understand that the regression tests often use very contrived data that doesn't resemble real-world model inputs, but I think a good solution is to add to our regression tests as needed when we find edge-cases in input data that aren't yet covered.

Is there an example of an instance where shipped some sample data that behaved unexpectedly, without crashing, and while our tests were passing?

**Comment by dcdenu4** [comment] 2021-02-24 15:16
I think this issue is still relevant though not critical. An idea that just occurred to me would be having nightly tests that ran against sample data on `main` and `release/*` branches of InVEST. This would be a low-impact, low-cost way of solving what I think is the main issue; catching critical bugs on "real" data that slipped through the tests before finding them on release day. Did I use a semi-colon right there? Having GRE flashbacks.

**Comment by phargogh** [comment] 2021-09-17 23:51
We talked about this today and thought that while it's valuable to run something akin to `invest-autotest` once in a while, it might not be worth running on every push (like our tests currently are)

As a compromise, we thought that running all models with the sample data would be a good baseline:
* Every time a commit to `main` or `release/*` (which should just be when a PR into one of those branches is merged)
* Nightly on each branch

Running nightly will give us the added benefit of helping us to identify if/when a problematic package has been released.

**Comment by emlys** [comment] 2022-01-03 19:25
Not having this set up gave us a lot of trouble with the 3.10 release, so I'd like to prioritize this before the next release.

**Comment by davemfish** [comment] 2022-01-03 21:26
> Not having this set up gave us a lot of trouble with the 3.10 release, so I'd like to prioritize this before the next release.

Agreed. And to clarify while it's still fresh: not having run models on their sampledata in a very long time caused us trouble during the release. So some sort of scheduled runs of `invest-autotest` would be great. I still don't think we need to go so far as to test the results of those runs against regression data.

**Comment by dcdenu4** [comment] 2022-01-04 17:22
We talked about this again today in a call and will go ahead with:

- [ ] Create a nightly build for `main` and `release` that uses `invest-autotest` to check against InVEST sampledata
- [ ] The InVEST sampledata action run should be able to be run on demand
- [ ] Add a point to the PR template to remind ourselves of running any model UIs if needed

**Comment by davemfish** [comment] 2023-01-24 15:20
> Create a nightly build for main and release that uses invest-autotest to check against InVEST sampledata

I'm not sure this is possible as github only supports cron jobs for a repo's default branch. Technically we can have the job on `main` checkout the `release` branch and then build & test from there. But it's messy because changes to the workflow file would need to be committed on `main` before they could be applied to a run on `release`. 
See https://github.com/community/community/discussions/16107

A simpler solution might be just run the autotest on pushes to `main` or `release`. i.e. on the merge commit of a PR. Or run the autotest on all our usual triggers, it adds ~10 minutes of runtime.

**Comment by davemfish** [comment] 2023-03-03 16:44
Done in #1158

**Closed by davemfish** 2023-03-03 16:44 UTC
Labels: enhancement, question, in progress
