### ISSUE TITLE
Question: in SWY model is it possible to use simple D8 flow direction instead of MFD 

### ISSUE THREAD

**Issue by silviafranceschi** [natcap/invest#528] opened 2021-03-25 16:58 UTC
Dear all,
I would ask you if you think that it is possible to use the standard D8 flow direction instead of the MFD in the SWY model. Using the D8 method would be an additional simplification of the model but it would be easier for me now to follow the path of the water and check the results.
I can access the source code so I can try to modify some call to functions or variables, but I am not sure what to change and if it will have consequences on all the rest of the code.

Any help and suggestion is very appreciated.

Thanks

Silvia

**Comment by emlys** [comment] 2021-03-25 17:21
The MFD algorithms that SWY uses have D8 counterparts in `pygeoprocessing`:  `flow_dir_d8`, `flow_accumulation_d8`, `extract_strahler_streams_d8` (I am not sure if this one is exactly interchangeable with `extract_streams_mfd`). You could swap those out. The cython functions `seasonal_water_yield_core.calculate_local_recharge` and `seasonal_water_yield_core.route_baseflow_sum` depend on MFD inputs. Changing that to use D8 would be more complicated. It may be a very difficult project if you're not already familiar with python, cython, and the invest codebase. 

> Using the D8 method would be an additional simplification of the model but it would be easier for me now to follow the path of the water and check the results.

If your interest in using D8 is just to be able to verify the results more easily, I would suggest checking out the [SWY test suite](https://github.com/natcap/invest/blob/main/tests/test_seasonal_water_yield_regression.py). The tests give us a reasonable level of confidence that everything is working as expected. You could also try running the model on a few small subsets of your data (10x10 pixels for example) where you can follow the flow direction, accumulation, and stream extraction steps, and check that everything makes sense. However if you do need D8 for a specific project, we could possibly help make a custom SWY modification. @richpsharp do you know if there's a scientific reason not to use D8 here?

**Comment by silviafranceschi** [comment] 2021-03-25 18:03
Thank @emlys for the quick reply.
Honestly my question comes because I would like to be able to use our tools to create flow directions and total contributing areas and then to extract the network and give to the SWY model this rasters instead of those calculated by the Invest tools.
To make this step by step I would start to change the maps using your maps of D8 and then substitute them with the ones calculated with our tools.

I would try to exchange those two functions and see, the only thing that I am not sure is that the output represent the same information, let me explain this. MFD and D8 have the same information in the pixels or not? is the convection for the flow directions the same? Regarding stream it would be easier because the output should be the network 0-1 for network pixels.

The problem of the dependence of the calculation of the local recharge is something I saw but I can not evaluate so good... because I think that there are two main issues here:
1. the content of the maps obtained with the D8 method should have the same unit of measurement of the ones with MFD
2. there is the need to set the values of the variables beta and gamma both to 1, but will this be enough to make the models run with D8 instead of MFD?

A custom model would be so nice from your side but if you can assist me I would try to do the changes and let you know how it works, then if you will need to add some of the information to the base code I will be happy to contribute.

**Comment by phargogh** [comment] 2021-03-25 23:35
> I would try to exchange those two functions and see, the only thing that I am not sure is that the output represent the same information, let me explain this. MFD and D8 have the same information in the pixels or not? is the convection for the flow directions the same?

D8 and MFD have _very_ different representations of flow direction.  D8 uses a 1-byte integer value of 0-8 representing the direction of flow, while MFD uses a 32-bit mask representing fractional flow.

@silviafranceschi I took the liberty of switching out MFD for D8 in Seasonal Water Yield, which you can find in my fork at https://github.com/phargogh/invest/tree/feature/528-use-D8-in-SWY.  You'll probably want to use git to pull those changes into your local copy.  Fair warning: I've only eyeballed these outputs (they look reasonable), and they don't have the usual rigor of testing that we would use if we included this change in InVEST.

---

@emlys , you're right that `extract_strahler_streams_d8` is quite different from `extract_streams_mfd` ... [Strahler stream order](https://en.wikipedia.org/wiki/Strahler_number) describes a tree of tributaries, and so the "extraction" there is creating a vector of line segments where each segment has an attribute with the numeric order.  By contrast, `extract_streams_mfd` produces a raster indicating which pixels are streams.  The reason there isn't a `extract_streams_d8` is that such a function is merely a call to `raster_calculator`.

**Comment by silviafranceschi** [comment] 2021-03-26 15:30
Thanks @phargogh for the fork, really very nice from your side.
I downloaded the two files and substituted them into my installation working in the IDE (sorry but I am not smart enough to change the whole code in this installation yet...).
I have two questions:
1. did you changed only the two files `seasonal_water_yield.py` and `seasonal_water_yield_core.pyx`?
2. unfortunately there are some problems with nodata at a certain point during the elaboration of the `L_sum_avail` and `Vri` maps; in the output raster is evident but there are also some error messages in console: 

> Task._call(1234) ERROR flow dir nodata? this makes no sense

I am trying to understand what is that makes this happens but I am very slow. Do you have any idea on a possible solution?

Thanks again for all the help and patience you have with me...

**Comment by silviafranceschi** [comment] 2021-04-02 07:50
Dear @phargogh, sorry for bothering you... do you have any idea on how to solve my problem with this issue on the modified D8 flow directions?

I am stuck here and can not understand where the mismatching of the NODATA values origins.

Thanks

Silvia

**Comment by richpsharp** [comment] 2021-04-07 01:37
Hi @silviafranceschi, just FYI I wrote the original implementation of SWY as well as the MFD algorithm that is in the invest core. I appreciate what you're asking for here, but it is not as easy as it might conceptually seem. There is a lot of custom routing code with SWY involving systems of linear equations and discontinuities. There's a lot of code wrapped up into how to average those between the possible converging and diverging flow directions let alone the implementation of the flow algorithm. I think it is a good idea to have a D8 version of this though, but we're talking about many hours of programming time, let alone the long term testing, maintenance, and overall mission of the software project as guided by the natural capital project.

There are a few ways we could do this, but in general it would require us reallocating funds or raising them directly. Is the project you're working on have a scope of that nature? Or is there any other information you have that could help us out here?

**Comment by silviafranceschi** [comment] 2021-04-08 15:56
Hi @richpsharp, thanks for the reply.
@phargogh did a lot of work for quickly changing the MFD to D8 and there is now only a problem on two maps for the management of the Nodata values. In my honest opinion the simplified D8 flow direction is an option that many users will evaluate running the model because it allows the user to easily understand the data and to compare the extraction of the stream network with one done in any other GIS application.
What I would like to do in my work is to replicate the SWY model outside Invest in order to have a very simple application that can be run to evaluate a rough water budget at at least monthly scale. I think that this model is a valid option when you do not have detailed data and for big regions, but I still do not have the complete context to evaluate this option.
Regarding the using of the flow direction to follow the network upstream and downstream, I have already something but I have to verify that what SWY model needs is available somehow. 
So for me it is important to have a base to compare data and results of my model on a testcase. I am sorry for bothering you, but I thought that these requests were of interest of others too.
Unfortunately I do not have enough budget to make you doing this work and will not force anyone to do this, it was an idea and I thought this could be useful also for others.

Thanks!

**Comment by emlys** [comment] 2021-09-27 18:37
Closing this since it seems the original question was addressed. If there is more interest and funding in the future for adding D8 to SWY we can make new PEP ticket.

**Closed by emlys** 2021-09-27 18:37 UTC
