### ISSUE TITLE
Check all models for mismatched args spec

### ISSUE THREAD

**Issue by emlys** [natcap/invest#305] opened 2020-09-09 22:29 UTC
https://community.naturalcapitalproject.org/t/water-yield-output-error/1315
This looks to be an error introduced/uncovered by this PR: https://github.com/natcap/invest/pull/273
The hydropower UI file includes the arg `do_scarcity_and_valuation`, which doesn't exist in the model `ARGS_SPEC`, and because of the changes I made in this validation PR, args that don't have a match cause a `KeyError`. I guess this slipped through the tests. We should check the other models for mismatched args. This won't be a problem in the workbench because the UI will reference the `ARGS_SPEC` directly.

**Comment by phargogh** [comment] 2020-09-09 23:13
Hey @emlys it's quite possible that this change to validation might affect other models as well, not just the annual water yield model.  InVEST has historically been very permissive about the args that are allowed to be provided to the model, only using the ones that it needs.  Changing this behavior will also end up being a breaking change for anyone who happens to be passing in any keys to args that are unused, provided that the model calls the `validate` function within `execute` (which a fair number of models do).  I'm sorry I failed to catch this as part of the PR!

Given the bugfix from PR #273 , is it possible for us to allow args that are not used to be passed in to the model?

**Comment by emlys** [comment] 2020-09-10 00:38
> Given the bugfix from PR #273 , is it possible for us to allow args that are not used to be passed in to the model?

I just looked through all the models, and hydropower seems to be the only one with this problem. We definitely could ignore `KeyError`s from that line in validation. I was thinking this was actually a good thing because it revealed some outdated sample data and UI args (this one just slipped through the tests). 

Agreed that we should allow the UI to have inputs that aren't in the `ARGS_SPEC`, but I would think those should be pre-defined and strictly limited to things we know aren't relevant to the model logic. If we just ignore any input that isn't recognized, mistakes like this could slip in again. For instance if we rename an arg and forget to change it both places, it simply won't be validated. Seems like that could lead to some more confusing problems.

Would it make sense to add an optional set of automated tests that run each model with the sample data and just check that there aren't any errors? Maybe not worth running every time, but before a release? Something like that would've caught this bug, and then we could be sure that the sample data is fully up-to-date.

**Comment by phargogh** [comment] 2020-09-10 18:12
> I just looked through all the models, and hydropower seems to be the only one with this problem.

That's great!  I'm glad this isn't more widespread.  We'll still want to issue a bugfix release once a fix for this is in so that anyone else running the annual water yield model is able to without downgrading.

> I was thinking this was actually a good thing because it revealed some outdated sample data and UI args (this one just slipped through the tests)

It _is_ a good thing that this came up, but it is definitely _not_ a good thing that we shipped software that broke under reasonable inputs.  Our tests should indeed have caught this before the release, and it would be good for us to ensure that our models can run before we do a release (see note below about `invest-autotest`.

> Agreed that we should allow the UI to have inputs that aren't in the ARGS_SPEC, but I would think those should be pre-defined and strictly limited to things we know aren't relevant to the model logic.  If we just ignore any input that isn't recognized, mistakes like this could slip in again. For instance if we rename an arg and forget to change it both places, it simply won't be validated. Seems like that could lead to some more confusing problems.

InVEST's expected behavior (ignore keys in `args` that it isn't using) is consistent with python's duck typing: If it looks like a duck and quacks like a duck, then it's a duck.  In our case, if it looks like a valid `args` dict and operates like a valid `args` dict (i.e. has the keys it needs), then it's a valid `args` dict.  We don't need to impose extra rules about the structure of the dict, and providing an extra key isn't breaking the contract.  Note that this is _not_ the case in other languages and standards!  Many RESTful APIs for example are _very_ strict about what is and is not allowed, and sometimes that strictness is built in to the language (e.g. Java interfaces).  But it isn't the case with python and we need not impose extra structure (and long-term maintenance work for us!) where it's not needed.

You do make a great point about programmer error ... why not try to protect ourselves against our own mistakes?  This is a great point!  But I don't think enforcing these restrictions on all users at runtime is the right solution to this problem.  As the developers of InVEST, we also have access to our whole development and test environment and we can verify through testing, linters, scripts, etc. that all of our keys line up as expected.  I'd suggest that we add a test or some other form of automated check to let us know when something isn't lining up.  No need to enforce this on our users at runtime.

> Would it make sense to add an optional set of automated tests that run each model with the sample data and just check that there aren't any errors? Maybe not worth running every time, but before a release? Something like that would've caught this bug, and then we could be sure that the sample data is fully up-to-date.

Absolutely!  We do have an existing script that does this (more or less) on a built binary that lives at `scripts/invest-autotest.py`.  I would call it largely functional, but not reliable for automated tests.  Plus, running every model on the full set of sample data takes quite some time.  In any case, I think you're right that running such a test suite would be wise for us to do before doing a release as a precaution and I've added it to the bugfix release checklist until we can automate a test or tests of this sort.

**Comment by emlys** [comment] 2020-09-10 19:04
> InVEST's expected behavior (ignore keys in `args` that it isn't using) is consistent with python's duck typing: If it looks like a duck and quacks like a duck, then it's a duck. In our case, if it looks like a valid `args` dict and operates like a valid `args` dict (i.e. has the keys it needs), then it's a valid `args` dict. We don't need to impose extra rules about the structure of the dict, and providing an extra key isn't breaking the contract. Note that this is _not_ the case in other languages and standards! Many RESTful APIs for example are _very_ strict about what is and is not allowed, and sometimes that strictness is built in to the language (e.g. Java interfaces). But it isn't the case with python and we need not impose extra structure (and long-term maintenance work for us!) where it's not needed.

Just for the sake of discussion and understanding your point I'm going to argue the other side for a minute 🙂 Why shouldn't the UI args passed to the model (not including any properties relevant only to the UI; I believe in the workbench this is `argsSpec` vs. `uiSpec`) and the model ARGS_SPEC share an identical structure? Especially given that, in the workbench, `argsSpec` _is_ `ARGS_SPEC` accessed through the server? I would think the contract should be that `set(args.keys()) == set(ARGS_SPEC.keys())`, and any extraneous args shouldn't be passed to the model at all.

> But I don't think enforcing these restrictions on all users at runtime is the right solution to this problem. As the developers of InVEST, we also have access to our whole development and test environment and we can verify through testing, linters, scripts, etc. that all of our keys line up as expected.

That also means that we can guarantee which args are/aren't passed to the model; the user shouldn't be able to change that. I don't really see this as a restriction on the user because, with more thorough testing, we should be able to guarantee that this case won't happen again.

IMO, especially now that with the workbench the UI and model logic are separated by a server, there should be a clear distinction between _model inputs_ that are shared between the components, and _UI inputs_ that are only relevant to the UI. For maximum separation of the components I'd think we should not let any unnecessary args be shared with the model backend.

Happy to change it back to allowing extra args if you think that's best though!

**Comment by phargogh** [comment] 2020-09-10 21:54
Just to summarize our conversation this afternoon, we talked about the distinction between what's allowed in the various interfaces, and the degree of isolation that should exist between layers.  @emlys you make great points that I completely agree with about:

* the UI should _not_ be providing the python layer with any information about the implementation of the UI
* the model layer should _not_ depend on any implementation details of the UI layer
* we should avoid having implementation details accidentally leak through the UI layer into the model layer

We completely agree on these points!  And the only thing that I insisted on was that if there are extra keys provided to `args` that are not used by a given `execute`, that this is not an error state and the model should not be prevented from running with these extra keys.  Scripting with the InVEST API is a good example of a use case when some other args keys might be provided and we won't have complete control over the keys being provided to an `execute` function.  The flask server used for the workbench is a different use case, and there will be other considerations for what is reasonable validation and checking on that interface.

Anyways, you also had a broader point about having our tests include some tests to help catch errors that would prevent a user from running a model through one of the standard interfaces, which is a great idea!  And `invest-autotest` might be a good starting point for some further testing, but it's almost certainly not as replete or stable (or as fast) as it should be for us to use it as part of our regular automated testing.

Sounded like once you have a chance to fix this in the model, we'll issue a 3.8.9 release!

**Closed** 2020-09-14 20:51 UTC
Labels: bug, in progress
