### ISSUE TITLE
model start menu icons are blank

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#320] opened 2020-09-24 20:54 UTC
I'm seeing this in 3.8.9. Not sure how far back in the releases it goes.

**Comment by phargogh** [comment] 2020-09-24 21:01
On my windows computer, this appears to be an issue with InVEST 3.8.8 and later.  InVEST 3.8.7's start menu icons appear as I would expect them to be.

**Comment by phargogh** [comment] 2020-09-29 17:18
While testing binaries for #314 on a fresh Windows VM, it appears that some (but not all) of the icons are loading:

<img width="284" alt="Screenshot 2020-09-29 101705" src="https://user-images.githubusercontent.com/4583897/94591617-257ad680-023d-11eb-9f8a-12548866b123.png">

**Comment by dcdenu4** [comment] 2020-10-08 12:23
I can confirm that when restarting Windows the previously blank icons are now fixed. Seeing as we have not changed anything with regards to the NSIS installer, this sounds like a Windows hitch.

**Comment by dcdenu4** [comment] 2020-10-08 12:36
Tried to do some light Googling, but this could be a rough debug. @phargogh @davemfish When you guys use Windows VMs for testing are the Windows versions consistent or are they updated with patches like a normal Windows desktop?

**Comment by davemfish** [comment] 2020-10-08 15:36
I only tested this on my desktop. It sounds like we're confident this is not an issue with our software, so I would be happy to close this issue.

**Comment by dcdenu4** [comment] 2020-10-09 12:07
Going to close this issue since there doesn't appear to be anything we could / should do about it at this point.

**Closed by dcdenu4** 2020-10-09 12:07 UTC
Labels: task

**Comment by phargogh** [comment] 2020-10-12 19:00
No need to reopen, just wanted to mention that after installing [InVEST 3.5.0 for a forums question](https://community.naturalcapitalproject.org/t/overlay-analysis-helper-tool-data-format/1403), the icons were also not showing up.  So this must be an issue with windows and not something we should have to worry about.
