### ISSUE TITLE
User reported UCM UI input lag after multiple runs

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#268] opened 2020-08-17 19:41 UTC
A user on the forums posted that they were experiencing significant slow downs in the interaction with the UI after running the UCM model 50+ times. They mention that changing trivial inputs and parameters would cause the UI to hang for minutes. Their self reported fix was to clear the cache.

https://community.naturalcapitalproject.org/t/urban-cooling-model-taking-a-really-long-time-to-parameterize/1242/4?u=dcdenu4

**Comment by emlys** [comment] 2021-06-02 20:56
Lingling recently reported the UI lagging when she tried out SDR (copied from slack):
> Hi all, today I downloaded INVEST 3.9 and wanted to test run SDR. Here it is what I experience:
It took me a while to set all inputs. This is because the UI window shows no responding for a while when I clicked. I am not sure if it is related to my laptop or SDR code? Any thoughts? 

> Are you running on a Windows or Mac?
       - Windows
Are your file inputs locally stored or on a remote drive?
       - Local
Do you notice it slow down after trying to load a certain input?
       - It started to slow down from watersheds, especially biophysical table (1 mins or so).  Then threshold flow accumulation takes 15s,  k takes 1 mins or so. (I tried two times)
Does shipped InVEST sample data load and run okay?    
      - I am going to try this one. (edited)

**Comment by emlys** [comment] 2021-12-17 01:24
I'm labeling this with "icebox" because it hasn't been reproduced and the Qt UI will be deprecated soon anyway.

**Comment by emlys** [comment] 2023-03-08 00:23
Closing because we deprecated the QT interface!

**Closed by emlys** 2023-03-08 00:23 UTC
Labels: icebox, qt ui
